# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args:
            - --max-line-length=100

-   repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'  # add version here
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
        args:
          - "--no-update"
